GHAction - add test for version consistency
We do unfortunately (at least right now) pick up the version via
2 different means, they need to be kept in sync.

files/pe-utils/versions.json:    "version" : "2.6.0-dev"
snap/snapcraft.yaml:version: "2.6.0-dev"

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -98,6 +98,25 @@ jobs:
           pelion-edge.version
           pelion-edge.edge-testnet
           pelion-edge.curl --version
+      - name: Check snap-pelion-edge versions
+        run: |
+          snap install yq  
+          snapcraftyamlver=$(yq -r ".version" <snap/snapcraft.yaml |sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g")
+          version=$(pelion-edge.version |grep snap-pelion-edge | awk -F' ' '{ print $NF }')
+          if [[ "$snapcraftyamlver" != "$version" ]]; then
+              echo "FAIL - Snapcraft.yaml and pelion-edge.version versions differ: $snapcraftyamlver vs. $version"
+              exit 1
+          fi
+          snapver=$(snap list |grep "pelion-edge" | awk -F' ' '{ print $2 }')
+          if [[ "$snapcraftyamlver" != "$snapver" ]]; then
+              echo "FAIL - Snapcraft.yaml and snap list versions differ: '$snapcraftyamlver' vs. '$snapver'"
+              exit 1
+          fi
+          infover=$(pelion-edge.edge-info |grep "Pelion Edge Version:" | awk -F' ' '{ print $NF }' |sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" )
+          if [[ "$snapcraftyamlver" != "$infover" ]]; then
+              echo "FAIL - Snapcraft.yaml and pelion-edge.edge-info versions differ: '$snapcraftyamlver' vs. '$infover'"
+              exit 1
+          fi
 
 # Disabled for now - reboot is required to get installation working correctly,
 # we cannot however reboot a GitHub runner mid-job.
